export const NAV: Record<string, { to: string; label: string }[]> = {
  PUBLIC: [
    { to: "/", label: "Home" },
    { to: "/projects", label: "Projects" },
    { to: "/announcements", label: "Announcements" },
    { to: "/reels", label: "Development Reels" },
    { to: "/emergency", label: "Emergency" },
    { to: "/directory", label: "Municipal Directory" },
    { to: "/login", label: "Login" },
  ],
  CITIZEN: [
    { to: "/app", label: "Dashboard" },
    { to: "/app/complaints", label: "Complaints" },
    { to: "/app/complaints/new", label: "Submit" },
    { to: "/app/nearby", label: "Nearby issues" },
    { to: "/app/projects", label: "Projects" },
    { to: "/app/reels", label: "Reels" },
    { to: "/app/announcements", label: "Announcements" },
    { to: "/app/feedback", label: "Feedback" },
    { to: "/app/emergency", label: "Emergency" },
    { to: "/app/cleaning", label: "Cleaning" },
    { to: "/app/profile", label: "Profile" },
  ],
  NAGAR_SEVAK: [
    { to: "/app/ward", label: "Ward Overview" },
    { to: "/app/complaints", label: "Complaints" },
    { to: "/app/projects", label: "Projects" },
    { to: "/app/reels", label: "Development Reels" },
    { to: "/app/announcements", label: "Announcements" },
    { to: "/app/feedback", label: "Feedback" },
    { to: "/app/cleaning", label: "Cleaning" },
    { to: "/app/analytics", label: "Analytics" },
  ],
  OFFICER: [
    { to: "/app/officer", label: "Queue" },
    { to: "/app/complaints", label: "Complaints" },
    { to: "/app/projects", label: "Projects" },
    { to: "/app/evidence", label: "Evidence Review" },
    { to: "/app/analytics", label: "Analytics" },
  ],
  ENGINEER: [
    { to: "/app/engineer", label: "Projects" },
    { to: "/app/complaints", label: "Related Complaints" },
    { to: "/app/analytics", label: "Analytics" },
  ],
  CONTRACTOR: [
    { to: "/app/contractor", label: "Assigned Projects" },
    { to: "/app/projects", label: "Progress" },
  ],
  ADMIN: [
    { to: "/app/admin", label: "Dashboard" },
    { to: "/app/admin/users", label: "Users" },
    { to: "/app/admin/roles", label: "Roles & Permissions" },
    { to: "/app/complaints", label: "Complaints" },
    { to: "/app/projects", label: "Projects" },
    { to: "/app/reels", label: "Reels" },
    { to: "/app/announcements", label: "Announcements" },
    { to: "/app/feedback", label: "Feedback" },
    { to: "/app/emergency", label: "Emergency" },
    { to: "/app/directory", label: "Directory" },
    { to: "/app/analytics", label: "Analytics" },
    { to: "/app/admin/audit", label: "Audit Logs" },
  ],
};
